### ISSUE TITLE
Keep monitor pod to debug

### ISSUE THREAD

**Issue by lhy1024** [lhy1024/bench#17]
I plan to provide this functionality through the api_server, the detailed process is:

1. After each invocation of the workload finished, api_server uses the `rsync` to backup Prometheus data and Grafana dashboard configuration files to an S3 backend.
2. Api_server supplies an API to search for all related monitoring data backups.
3. Api_server supplies an API to launch the Prometheus and Grafana dashboard pods on a K8s cluster and uses the backup data to restore the metrics.

**Comment by mahjonp** [comment]
https://github.com/pingcap/tipocket/pull/305
